130 adding asterick in required input field namephone and dob and removing default showing of choose option from the gender input field
hamrolifebank/donor-pwa pull request #185
Opened 2022-12-09 06:15 UTC by amirthapamagar2053

2022-12-09 09:20 UTC, rushilshakya requested changes

2022-12-09 09:20 UTC, rushilshakya commented on src/sections/form/index.js
> +  // startDate: null,
remove commented code

2022-12-09 09:20 UTC, rushilshakya commented on src/sections/form/index.js
> +const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
put these values in config

2022-12-09 09:20 UTC, rushilshakya commented on src/sections/form/index.js
> +const genders = ["male", "female", "other"];
put in config file

2022-12-09 09:20 UTC, rushilshakya commented on src/sections/form/index.js
> +  // age: Yup.number()
remove commented out code

2022-12-09 11:36 UTC, SurazGaire approved these changes

2022-12-12 09:43 UTC, rushilshakya approved these changes

2022-12-12 09:43 UTC, merged